internal/crypto/pq.go

Old:
```
goos: windows
goarch: amd64
pkg: github.com/gotd/td/internal/crypto
BenchmarkDecomposePQ
BenchmarkDecomposePQ-4   	      16	 707597638 ns/op	33065308 B/op	 3485209 allocs/op
PASS
```
New: 
```
goos: windows
goarch: amd64
pkg: github.com/gotd/td/internal/crypto
BenchmarkDecomposePQ
BenchmarkDecomposePQ-4           26   541487342 ns/op    863167 B/op    107167 allocs/op
PASS
```
benchcmp
```
benchmark                  old ns/op     new ns/op     delta
BenchmarkDecomposePQ-4     707597638     541487342     -23.48%
benchmark                  old allocs     new allocs     delta
BenchmarkDecomposePQ-4     3485209        107167         -96.93%
benchmark                  old bytes     new bytes     delta
BenchmarkDecomposePQ-4     33065308      863167        -97.39%
```

Re-use big.Int in DecomposePQ

---

bin/buffer.go
internal/proto/codec/codec.go
internal/proto/codec/full.go
internal/proto/codec/intermediate.go
internal/proto/gzip.go
internal/proto/gzip_test.go
telegram/client_e2e_test.go
telegram/internal/tgtest/server.go

Limit gzip decompressed data reader with maximum of 10 mb.

feat(proto): mitigate possible DOS in gzip decoding

---

telegram/client_e2e_test.go
telegram/internal/tgtest/conns.go
telegram/internal/tgtest/loop.go
telegram/internal/tgtest/server.go

- use `*zap.Logger` instead of `*testing.T` to log
- remove unused field in server

Some fixes in tgtest

---

telegram/read_loop.go
telegram/reconnect.go
telegram/reconnect_test.go

* Handle more unrecoverable connection errors
* Don't reconnect if client is done
Fix #77

feat(telegram): improve reconnect

---

internal/crypto/rsa.go
telegram/internal/exchange/flow_test.go
telegram/internal/exchange/proto.go

Now uses `new(big.Int)` instead of `big.NewInt(0)`.
`big.NewInt(0)` may add unwanted zero byte to `big.Int` buffer.

Fix RSA (en/de)cryption

---

telegram/auth.go
telegram/auth_flow.go
telegram/auth_user.go
telegram/client_external_test.go

Handle sign up and term of service in AuthFlow.
This is required for end-to-end tests.

feat(telegram): implement sign up flow

---

telegram/auth_flow.go

This method seems to be to accept TOS updates for existing users. It looks like by signing up you automatically accept the TOS.
> By signing up for Telegram, you agree not to: ...
This method is not in the [list of methods](https://core.telegram.org/api/auth#we-are-authorized) available to unauthorized users.

fix(telegram): don't client.AuthAcceptTOS

---

internal/crypto/cipher_decrypt.go
internal/crypto/cipher_decrypt_test.go
internal/exchange/client_flow.go
internal/exchange/client_flow_test.go
internal/exchange/flow_test.go
telegram/internal/tgtest/loop.go
telegram/internal/tgtest/server.go
telegram/message/doc.go
telegram/message/format.go
telegram/message/format_test.go

Add text formatters, add some crypto checks 

---

internal/proto/message_id.go
internal/proto/message_id_test.go
mtproto/conn.go
mtproto/read.go

feat: message id buffer

---

internal/tdsync/reset_ready_test.go
mtproto/conn.go
mtproto/ping.go

In the current implementation pong callback was setting after ping request.
This may cause a problem when:
1. Client sent ping request
2. Server responded with pong
3. Client received pong, but callback for that pong not found
4. Client sets pong callback, but it will never be called because we already received pong before
5. Client disconnects because pong was 'missed'.
This PR should fix that.

chore(mtproto): slightly rework ping-pong logic

---

internal/exchange/client_flow_test.go
internal/exchange/flow_test.go
internal/pool/req_map_test.go
internal/tdsync/cancel_group.go
internal/tdsync/cancel_group_test.go
internal/tdsync/log_group.go
telegram/client.go
telegram/client_mtproxy_test.go
telegram/downloader/parallel.go
telegram/downloader/stream.go
telegram/uploader/big.go
transport/server.go

* Use `g` for group variable name
* Use fooMux for mutex names
* Use `ctx` for context parameter name

refactor: ensure groups naming consistency

---

internal/gen/_template/main.tmpl
internal/gen/example/tl_send_multiple_sms_gen.go
internal/gen/make_field.go
tg/tl_help_config_simple_gen.go

This PR fixes an edge case where _bare vectors of singular types_ (classes with one constructor) were decoded as _bare vectors of __bare__ types_.

fix(gen): bare vectors don’t imply bare encoders

---

telegram/handle_updates.go

fix(telegram): updateShortMessage fix 'FromID' field

---

telegram/message/entity/formatter.go
telegram/message/entity/html.go
telegram/message/entity/html_test.go
telegram/message/entity/options.go
telegram/message/entity/options_test.go
telegram/message/html/html.go
telegram/message/html/html_example_test.go
telegram/message/html_test.go
telegram/message/styling/option.go

Use `InputMessageEntityMentionName` instead of `MessageEntityMentionName`.

fix(entity): fix MentionName entity formatter

---

internal/rpc/engine.go

This change makes the RPC engine drop the request when parent context reaches deadline.
That is, before this change a deadline from context.WithTimeout would not drop the request.

fix(rpc): drop request on context deadline

---

internal/testutil/external.go

Check that all callers of SkipExternal helper are
named correctly.

test(e2e): assert caller for SkipExternal

---

telegram/invoke.go
telegram/migrate_to_dc_test.go

Now it detects migration error using `_MIGRATE` suffix

fix(telegram): migrate even if error code is not equal to 303

---

go.mod
internal/proto/gzip.go
internal/proto/gzip_test.go

Benchstat results:
```
name                    old time/op    new time/op     delta
GZIP_Encode/16b-12         102µs ± 4%       19µs ± 1%   -81.77%  (p=0.008 n=5+5)
GZIP_Encode/128b-12        120µs ± 2%       32µs ± 3%   -72.87%  (p=0.008 n=5+5)
GZIP_Encode/1024b-12       170µs ± 6%       74µs ± 5%   -56.42%  (p=0.008 n=5+5)
GZIP_Encode/8192b-12       237µs ± 1%      140µs ± 1%   -40.81%  (p=0.008 n=5+5)
GZIP_Encode/65536b-12     1.28ms ± 1%     1.04ms ± 1%   -18.86%  (p=0.008 n=5+5)
GZIP_Encode/524288b-12    9.65ms ± 0%     8.83ms ± 1%    -8.49%  (p=0.008 n=5+5)
GZIP_Decode/16b-12        5.62µs ± 2%     0.79µs ± 2%   -85.85%  (p=0.008 n=5+5)
GZIP_Decode/128b-12       5.43µs ± 0%     0.66µs ± 1%   -87.78%  (p=0.016 n=4+5)
GZIP_Decode/1024b-12      5.69µs ± 1%     1.00µs ± 0%   -82.43% …
```

feat(proto): add GZIP pooling

---

telegram/updates/engine.go

>Got UpdateChannelTooLong without pts field
Seems to be a pretty common warning and doesn’t require human intervention, so should probably be Info instead of Warn.

chore(updates): reduce warn log to debug

---

telegram/internal/manager/conn.go

This change should fix a bug where session data is overwritten with empty config
without current DC ID thus rendering client that uses session storage completely
unusable since it would indefinitely retry connection to non-existent DC ID 0.
For reference, the symptom of the bug is a “Got error on self” log message spam
and of course corrupted data in session storage.

fix: don’t initialize config on error

---

.golangci.yml
internal/mtproto/conn.go
internal/mtproto/options.go
internal/mtproto/read.go

Rework read loop to reduce idle memory consumption and deprecate "NoRese" option.
Delta for 16 threads:
```
name             old time/op    new time/op    delta
Read/16b-16         533ns ± 1%     518ns ± 2%   -2.72%
Read/128b-16        550ns ± 1%     548ns ± 1%   -0.35%
Read/1024b-16       795ns ± 1%    1006ns ± 2%  +26.49%
Read/8192b-16      3.59µs ± 1%    3.49µs ± 1%   -2.85%
Read/65536b-16     30.9µs ± 1%    15.8µs ± 2%  -48.67%
Read/524288b-16     173µs ± 1%     121µs ± 2%  -29.91%
name             old speed      new speed      delta
Read/16b-16      30.0MB/s ± 1%  30.9MB/s ± 2%   +2.80%
Read/128b-16      233MB/s ± 1%   234MB/s ± 1%   +0.35%
Read/1024b-16    1.29GB/s ± 1%  1.02GB/s ± 2%  -20.92%
Read/8192b-16    2.28GB/s ± 1%  2.35GB/s ± 1%   +2.94%
Read/65536b-16   2.12GB/s ± 1% …
```

feat(mtproto): use buffer pool in read loop

---

README.md

<details>
<summary>Preview</summary>
<table>
<tr>
<th>Topic</th>
<th colspan="2">gotd</th>
<th colspan="2"><a href="https://github.com/xelaj/mtproto">xelaj/mtproto</a></th>
<tr>
<td align="center">🚧<br>Maintainers</td>
<td colspan="2">At least 3 core contributors, 1.7K commits, actively maintained, <a href="https://github.com/gotd/td/pull/409">automatically updated to latest layer</a></td>
<td colspan="2">Single core contributor, 150 commits, effectively not maintaned from March 2021, <a href="https://github.com/xelaj/mtproto/issues/88">failed to update</a> to 129 layer</td>
<tr>
<td align="center">🔒️<br>Security</td>
<td colspan="2">MTProto v2, <a href="https://github.com/gotd/td/issues/155">conforms</a> to security guidelines</td>
<td colspan="2">MTProto v1 that is insecure and <a …

chore: prettify other projects comparison table

---

.golangci.yml
clock/system.go
internal/crypto/sha256.go
internal/gen/names.go
internal/mtproto/conn.go
internal/mtproto/options.go
internal/mtproto/read.go
internal/mtproto/read_test.go
internal/mtproto/vendored_keys.go
internal/mtproto/write.go
internal/mtproxy/faketls/tls.go
internal/proto/gzip.go
telegram/client.go
telegram/flood_wait.go
telegram/options.go

Initialize type mappings only once to decrease memory
consumption for multiple concurrent clients.
Also decrease goroutine count (remove worker model).

feat(telegram, mtproto): improve idle memory consumption

---

telegram/message/peer/resolve.go
telegram/message/peer/resolve_test.go

There are some special cases like `gif` or `pic`.

fix(peer): do not check username length

---

internal/mtproto/salts/salts.go
internal/mtproto/salts/salts_test.go

```
name            old time/op    new time/op    delta
Salts_Get-12       132ns ± 1%      15ns ± 1%   -88.87%  (p=0.000 n=10+10)
Salts_Store-12    90.6ns ± 7%   139.0ns ± 1%   +53.43%  (p=0.000 n=10+9)
name            old alloc/op   new alloc/op   delta
Salts_Get-12       96.0B ± 0%      0.0B       -100.00%  (p=0.000 n=10+10)
Salts_Store-12     0.00B         24.00B ± 0%     +Inf%  (p=0.000 n=10+10)
name            old allocs/op  new allocs/op  delta
Salts_Get-12        3.00 ± 0%      0.00       -100.00%  (p=0.000 n=10+10)
Salts_Store-12      0.00           1.00 ± 0%     +Inf%  (p=0.000 n=10+10
```

feat(salts): optimize salts storage

---

internal/crypto/keys.go

```
$ benchstat -geomean old.txt new.txt
name     old time/op    new time/op    delta
Keys-12     401ns ± 2%     381ns ± 1%  -5.13%  (p=0.000 n=23+21)
```

feat(crypto): reduce parameter copying and zeroing

---

telegram/updates/state_apply.go

Currently internal `applyCombined` and `applyPts` functions use state context instead of context passed while calling them. This leads to the loss of original context passed by user from higher layers.

Pass function scope context

---

telegram/auth.go
telegram/auth/auth.go
telegram/auth/status.go
telegram/connect.go
telegram/pool.go

fix(auth): improve unauthorized errors handling

---

telegram/updates/sort_pts.go
telegram/updates/sort_pts_test.go
telegram/updates/state_apply.go

fix(updates): sort updates before applying

---

.github/release.yml

- Stops listing the Dependa PRs in the auto-generated release notes.

chore: ignore dependency upgrades in release notes

---

telegram/client_external_test.go

test(e2e): enable TestExternalE2EUsersDialog

---

telegram/client.go

Put migration in the header of the structure to ensure 64-bit alignment, otherwise it will cause the atomic operation of connsCounter to panic.
https://pkg.go.dev/sync/atomic#pkg-note-BUG
fix #878

fix(telegram): 64-bit alignment of client struct

---

session/session.go
session/session_test.go
session/tdesktop.go
session/tdesktop_test.go
telegram/session.go

The tg.Config cannot be marshalled from json now,
fixing it and reducing it to subset.
This should be backward compatible.
Fix #885

fix(session): fix encoding, use tg.Config subset

---

telegram/auth/qrlogin/errors.go
telegram/auth/qrlogin/qrlogin.go

This change fixes the DC migration in `qrlogin` package.
>If, however, there is a DC mismatch between the two apps, [auth.loginTokenMigrateTo](https://core.telegram.org/constructor/auth.loginTokenMigrateTo) is returned instead, to which *the app that is trying to login should respond by calling [auth.importLoginToken](https://core.telegram.org/method/auth.importLoginToken) with the specified token, to the specified DC*.
https://core.telegram.org/api/qr-login

fix(qrlogin): import token after migration

---

telegram/message/inline/inline.go
telegram/message/markup/button.go
telegram/message/markup/inline_test.go
telegram/message/markup/keyboard_test.go

For inline:
* new builder for `switch_webview` parameter in [messages.setInlineBotResults](https://core.telegram.org/method/messages.setInlineBotResults).
And for markup I've added builders for all missing buttons:
* [inputKeyboardButtonUrlAuth](https://core.telegram.org/constructor/inputKeyboardButtonUrlAuth) — `InputURLAuth` + doc comment fix for `URLAuth`;
* [inputKeyboardButtonUserProfile](https://core.telegram.org/constructor/inputKeyboardButtonUserProfile) — `InputUserProfile` and [keyboardButtonUserProfile](https://core.telegram.org/constructor/keyboardButtonUserProfile) — `UserProfile`;
* [keyboardButtonWebView](https://core.telegram.org/constructor/keyboardButtonWebView) — `WebView` and [keyboardButtonSimpleWebView](https://core.telegram.org/constructor/keyboardButtonSimpleWebView …

feat(message): add missing inline & markup builders

---

telegram/client.go
telegram/client_test.go
telegram/options.go
telegram/transfer.go

- feat(clint): add OnTransfer callback
Fix: #1213 
Ref: #1301

feat(clint): add OnTransfer

---

examples/terminal.go

term.ReadPassword() requires an int. On windows passing syscall.Stdin without type casting fails.

Update terminal.go for windows os

---

telegram/message/html/html_example_test.go
telegram/message/html/parser.go
telegram/message/html/parser_test.go

[https://core.telegram.org/bots/api#html-style]
Added support for the tg-emoji(custom emojis) and blockquote tag
I also updated the test message from bot API docs adding the tg-spoiler, tg-emoji, and blockquote tags.

Update HTML Parser

---

telegram/uploader/big.go
telegram/uploader/helpers.go
telegram/uploader/uploader.go

[Streamed uploads](https://core.telegram.org/api/files#streamed-uploads)
- A total_stream_size variable must be used to keep track of the total number of bytes read from the stream.
- upload.saveBigFilePart must always be used, even if the stream turns out to be smaller than 10MB.
- The file_total_parts field must be set to -1 for all parts except for the last one, using the following logic:

feat(upload): add support for streamed uploads of Big File

---

examples/go.mod
examples/go.sum
telegram/connect.go

- **feat(telegram): reset backoff on connection ready**
- **chore(deps): update**

fix(telegram): reset backoff on connection ready

---

telegram/client.go
telegram/connect.go
telegram/options.go

feat(telegram): add OnSelfError
