gotd/td

- telegram/client.go
- telegram/cond_once.go
- telegram/cond_once_test.go
- telegram/handle_message_test.go
- telegram/read_loop.go
- telegram/reconnect.go
- telegram/rpc.go
> Wait until handleSessionCreated

- cmd/gotdecho/main.go
- telegram/client.go
- telegram/client_e2e_test.go
- telegram/client_external_test.go
- telegram/close.go
- telegram/read_loop.go
- telegram/write.go
Also removed unnecessary context in Close method
> Protect conn with mutex

- internal/gen/_testdata/example.tl
- internal/gen/example/tl_abstract_message_gen.go
- internal/gen/make_field.go
- tg/tl_global_privacy_settings_gen.go
- tg/tl_input_peer_notify_settings_gen.go
- tg/tl_keyboard_button_gen.go
- tg/tl_peer_notify_settings_gen.go
- tg/tl_phone_toggle_group_call_settings_gen.go
> fix(gen): handle conditional boxed bool

- mtproto/close.go
- mtproto/config.go
- mtproto/conn.go
- mtproto/conn_test.go
- mtproto/init_connection.go
- mtproto/options.go
- mtproto/read_loop.go
- mtproto/write.go
- telegram/client.go
- telegram/client_test.go
- telegram/invoke_raw.go
- telegram/migrate_to_dc.go
> feat: support dc migration

- .github/workflows/pr.yml
- telegram/builder.go
- telegram/client_external_test.go
- telegram/client_mtproxy_test.go
> Add MTProxy E2E test

- mtproto/handle_ack.go
- telegram/client.go
> Сall Self on reconnect to mark connection for updates

- telegram/client_e2e_test.go
- telegram/client_external_test.go
- telegram/client_mtproxy_test.go
- telegram/conn_builder.go
- telegram/internal/tgtest/loop.go
- transport/mtproxy.go
- transport/mtproxy_example_test.go
- transport/mtproxy_test.go
- transport/transport.go
- transport/transport_test.go
> Pass address and DC ID to transport

- telegram/pool.go
> fix(telegram): fix some DC creation bugs

- telegram/message/edit.go
- telegram/message/edit_test.go
- telegram/message/format.go
- telegram/message/html/html.go
- telegram/message/html_test.go
- telegram/message/internal/deeplink.go
- telegram/message/internal/deeplink/deeplink.go
- telegram/message/internal/deeplink/deeplink_test.go
- telegram/message/internal/deeplink_test.go
- telegram/message/join.go
- telegram/message/join_test.go
- telegram/message/peer.go
- telegram/message/peer/constraint.go
- telegram/message/peer/constraint_test.go
- telegram/message/peer/lru.go
- telegram/message/peer/lru_test.go
- telegram/message/peer/resolve.go
- telegram/message/peer/resolve_test.go
- telegram/message/peer/resolver.go
- telegram/message/peer/resolver_test.go
- telegram/message/peer_example_test.go
- telegram/message/peer_test.go
- telegram/message/sender.go
- telegram/message/text.go
- telegram/message/text_test.go
- telegram/query/hasher/hash.go
- telegram/query/hasher/hash_test.go
Fixes #184.
Fixes #186.
Fixes #227.
Fixes #231.
> Add some resolve features, add Textf function

- internal/syncio/writer_at.go
- internal/syncio/writer_at_test.go
- telegram/client_e2e_test.go
- telegram/client_external_test.go
- telegram/internal/helpers/upload.go
- telegram/internal/tgtest/loop.go
- telegram/internal/tgtest/send.go
- telegram/internal/tgtest/server.go
- telegram/internal/tgtest/services/file/download.go
- telegram/internal/tgtest/services/file/file.go
- telegram/internal/tgtest/services/file/storage.go
- telegram/internal/tgtest/services/file/upload.go
- telegram/message/peer.go
- telegram/message/peer/lru.go
- telegram/message/peer/resolver.go
- telegram/uploader/big.go
- telegram/uploader/part.go
- telegram/uploader/part_test.go
- telegram/uploader/uploader_test.go
> Add file service, some minor fixes

- internal/mtproto/conn.go
- internal/mtproto/write.go
> feat(mtproto): persist seqno for retries

- internal/mtproto/conn.go
- internal/mtproto/conn_test.go
- internal/mtproto/handle_ack.go
- internal/mtproto/handle_bad_msg.go
- internal/mtproto/handle_result.go
- internal/mtproto/msg_seq_test.go
- internal/mtproto/rpc.go
- internal/mtproto/write.go
- internal/rpc/ack.go
- internal/rpc/engine.go
- internal/rpc/engine_bench_test.go
- internal/rpc/engine_test.go
- telegram/client_test.go
- telegram/migrate_to_dc_test.go
> refactor(mtproto): remove internal request_id

- internal/mtproto/salts/salts.go
- telegram/message/peer/extract.go
- telegram/message/peer/user.go
- telegram/message/request.go
- telegram/message/request_test.go
- telegram/query/channels/participants/specialize.go
- telegram/query/channels/participants/specialize_test.go
- telegram/query/dialogs/iter.go
- telegram/query/dialogs/specialize.go
- telegram/query/dialogs/specialize_test.go
- telegram/query/messages/iter.go
- telegram/query/messages/specialize.go
- telegram/query/messages/specialize_test.go
- telegram/query/query_example_test.go
> Add some iterator element unpack helpers

- telegram/handle_updates.go
> fix(client): set Date for short updates

- telegram/flood_wait.go
- telegram/handle_updates.go
- telegram/internal/helpers/flood_wait.go
- telegram/internal/helpers/updates.go
- telegram/message/builder.go
- telegram/message/gif.go
- telegram/message/unpack/doc.go
- telegram/message/unpack/message.go
- telegram/message/unpack/message_example_test.go
- telegram/message/unpack/message_test.go
> Unpack helpers

- telegram/client.go
- telegram/message/peer/list.go
- telegram/message/peer/lru.go
- telegram/message/peer/lru_example_test.go
- telegram/message/peer/lru_test.go
- telegram/message/peer/resolver.go
- telegram/query/query.go
- telegram/query/query_example_test.go
> Add LRU resolver expiration support, add query shorthands

- internal/mtproto/handle_container.go
- internal/mtproto/handle_gzip.go
- internal/mtproto/handle_message.go
- internal/mtproto/handle_message_test.go
- internal/mtproto/read.go
- telegram/message/peer/extract.go
> Handle `msg_detailed_info` and `msg_new_detailed_info`

- telegram/message/entity/html.go
- telegram/message/file_promise.go
- telegram/message/file_promise_example_test.go
- telegram/message/html/html.go
- telegram/message/upload.go
- telegram/message/upload_test.go
- telegram/uploader/helpers.go
- telegram/uploader/progress.go
- telegram/uploader/source/doc.go
- telegram/uploader/source/http.go
- telegram/uploader/source/http_test.go
- telegram/uploader/source/source.go
- telegram/uploader/upload.go
- telegram/uploader/uploader.go
- telegram/uploader/uploader_test.go
> Add `FromURL` helper, some fixes

- go.mod
- go.sum
- internal/mtproxy/obfuscated2/keys.go
- telegram/client_external_test.go
- telegram/dcs/mtproxy.go
- telegram/dcs/protocol.go
- telegram/dcs/websocket.go
> feat(dcs): add websocket transport

- telegram/client.go
Expose internal tg.Client for convenience.
> feat(client): add API method

- internal/mtproto/conn.go
- internal/mtproto/new_encrypted_msg.go
- tgtest/loop.go
- tgtest/send.go
> feat(mtproto): gzip client messages

- README.md
- examples/README.md
- examples/auth/main.go
- examples/bot-auth-manual/main.go
- examples/bot-echo/main.go
- examples/bot-upload/main.go
- examples/examples.go
- examples/run.go
> docs(examples): add basic examples

- internal/rpc/engine.go
> chore: decrease drop request error log level

- telegram/client.go
> feat(telegram): same context in client

- README.md
- telegram/internal/manager/conn.go
- telegram/internal/manager/create.go
> fix(telegram): add retry backoff for initConnection

- telegram/client.go
> fix(telegram): save session after onReady

- cmd/gotdchats/main.go
- cmd/mtprint/printer.go
- cmd/rsagen/main.go
- examples/bot-upload/main.go
- gorules/rules.go
- internal/crypto/exchange.go
- internal/crypto/public_keys.go
- internal/crypto/rsa.go
- internal/crypto/srp/srp.go
- internal/exchange/generator.go
- internal/gen/generator.go
- internal/gen/make_structures.go
- internal/gen/write_source.go
- internal/mtproto/conn.go
- internal/mtproto/handle_message.go
- internal/proto/codec/abridged.go
- internal/proto/codec/codec.go
- internal/proto/codec/full.go
- internal/proto/codec/intermediate.go
- internal/proto/container.go
- internal/proto/unencrypted_message.go
- telegram/cdn.go
- telegram/flood_wait_test.go
- telegram/message/peer/lru_test.go
- telegram/message/peer_test.go
- tgerr/error_test.go
- tgtest/loop.go
- tgtest/send.go
https://github.com/uber-go/guide/blob/master/style.md#error-wrapping
> chore(gorules): add `UberStyleErrors` rule

- internal/wsutil/addr_test.go
- internal/wsutil/conn.go
- internal/wsutil/conn_test.go
- telegram/client.go
- telegram/client_e2e_test.go
- telegram/dcs/websocket.go
- telegram/migrate_to_dc.go
- tgtest/cluster.go
- tgtest/cluster_options.go
- transport/websocket.go
> fix(telegram): do not check DC list before migration

- internal/mtproto/conn.go
- internal/mtproto/read.go
- telegram/client_e2e_test.go
> fix(mtproto): wait handlers

- telegram/client.go
- telegram/get_version.go
> fix(telegram): read module version once

- internal/proto/codec/padded_intermediate.go
amd64 results:
```
name                                 old time/op    new time/op     delta
Write/PaddedIntermediate/16b-12         281ns ± 5%      141ns ± 1%   -49.60%  (p=0.008 n=5+5)
Write/PaddedIntermediate/128b-12        276ns ± 0%      142ns ± 2%   -48.55%  (p=0.008 n=5+5)
Write/PaddedIntermediate/1024b-12       275ns ± 1%      143ns ± 4%   -48.09%  (p=0.008 n=5+5)
Write/PaddedIntermediate/8192b-12       276ns ± 2%      141ns ± 1%   -48.92%  (p=0.008 n=5+5)
Write/PaddedIntermediate/65536b-12      276ns ± 1%      142ns ± 1%   -48.47%  (p=0.008 n=5+5)
Write/PaddedIntermediate/524288b-12     277ns ± 1%      142ns ± 1%   -48.78%  (p=0.008 n=5+5)
name                                 old speed      new speed       delta
Write/PaddedIntermediate/16b-12      71.3MB/s ± 5%  141.4MB/s ± 1% …
```
> refactor(codec): make PaddedIntermediate zero alloc using write buffer

- internal/crypto/rand_js.go
- internal/crypto/rand_notjs.go
- internal/exchange/flow.go
- internal/mtproto/options.go
- internal/proto/codec/padded_intermediate.go
- telegram/builder.go
- telegram/dcs/mtproxy.go
- telegram/dcs/websocket.go
- telegram/internal/e2etest/options.go
- telegram/message/sender.go
- telegram/options.go
- telegram/uploader/uploader.go
- tgtest/cluster/options.go
- tgtest/server_options.go
On `js/wasm`
```
name                              old time/op    new time/op      delta
Write/PaddedIntermediate/16b        15.4µs ± 4%       0.5µs ± 1%    -96.68%  (p=0.008 n=5+5)
Write/PaddedIntermediate/128b       14.9µs ± 2%       0.5µs ± 2%    -96.55%  (p=0.008 n=5+5)
Write/PaddedIntermediate/1024b      15.0µs ± 3%       0.5µs ± 1%    -96.57%  (p=0.008 n=5+5)
Write/PaddedIntermediate/8192b      15.1µs ± 2%       0.5µs ± 1%    -96.59%  (p=0.008 n=5+5)
Write/PaddedIntermediate/65536b     15.2µs ± 1%       0.5µs ± 0%    -96.64%  (p=0.008 n=5+5)
Write/PaddedIntermediate/524288b    15.3µs ± 2%       0.5µs ± 1%    -96.60%  (p=0.008 n=5+5)
name                              old speed      new speed        delta
Write/PaddedIntermediate/16b      1.30MB/s ± 4%   39.25MB/s ± 1%  +2909.66% …
```
> refactor(crypto): add DefaultRand function

- internal/mtproto/rpc_test.go
- internal/rpc/engine.go
- internal/rpc/external.go
- internal/rpc/external_test.go
- internal/rpc/options.go
> test(mtproto): add dropRPC test

- internal/ascii/ascii.go
- telegram/message/internal/deeplink/deeplink.go
- telegram/message/internal/deeplink/deeplink_fuzz_test.go
- telegram/message/internal/deeplink/deeplink_test.go
- telegram/message/internal/deeplink/domain.go
- telegram/message/internal/deeplink/domain_test.go
- telegram/message/join.go
- telegram/message/join_example_test.go
- telegram/message/join_test.go
- telegram/message/peer/resolve.go
- telegram/message/peer/resolve_test.go
> refactor(deeplink): ensure compliance with TDLib parser

- telegram/tljson/app_config.go
- telegram/tljson/app_config_test.go
- telegram/tljson/convert.go
- telegram/tljson/convert_test.go
- telegram/tljson/tljson.go
> feat(tljson): add AppConfig parser

- telegram/updates/manager.go
- telegram/updates/state.go
- telegram/updates/state_apply.go
- telegram/updates/state_channel.go
> fix(updates): context fixes for state manager

- README.md
https://go-review.googlesource.com/c/pkgsite/+/274276
> docs: add Links section to README

- internal/gen/names.go
- tg/tl_help_country_gen.go
- tg/tl_post_address_gen.go
- chore(gen): add ISO to acronyms
> chore(gen): add iso to initialisms

- session/tdesktop/tdesktop.go
> feat(stssion.tdesktop): make config optional

- .github/SUPPORT.md
- ROADMAP.md
- docs: update roadmap
- docs: update support doc about bans
> docs: update roadmap, support

- .golangci.yml
- examples/updates/main.go
- telegram/peers/integration.go
- telegram/peers/manager_example_test.go
- telegram/updates/access_hash_feeder.go
- telegram/updates/config.go
- telegram/updates/conv_shorts.go
- telegram/updates/doc.go
- telegram/updates/internal/e2e/manager_test.go
- telegram/updates/internal/e2e/storage_mem.go
- telegram/updates/manager.go
- telegram/updates/sequence_box.go
- telegram/updates/sequence_box_test.go
- telegram/updates/state.go
- telegram/updates/state_apply.go
- telegram/updates/state_channel.go
- telegram/updates/storage.go
- telegram/updates/storage_mem.go
- telegram/updates/update.go
- feat(examples): enrich userbot example
- feat: total rework of update handling
> feat(updates): rework

- examples/gif-download/main.go
- examples/terminal.go
- examples/updates/main.go
- examples/userbot/main.go
> chore(examples): use terminal auth everywhere

- README.md
- chore: depguard
- chore: upd
- docs(readme): mention gotgproto
- docs(readme): fix link
> docs(readme): fix link

- telegram/internal/upconv/upconv.go
> fix(upconv): properly convert ReplyTo

- telegram/peers/options.go
- Fixed panic in peers.Manager during updates
> fix(telegram): panic in peers.Manager during updates
